### ISSUE TITLE
Allow using the Selenium standalone server

### ISSUE THREAD

**Issue by analog-nico** [mojotech/pioneer#265]
The installation instructions of selenium-webdriver say:

    In addition to the npm package, you will have to download the WebDriver
    implementations you wish to utilize. As of 2.34.0, `selenium-webdriver`
    natively supports the ChromeDriver.
    Simply download a copy and make sure it can be found on your `PATH`. The other
    drivers (e.g. Firefox, Internet Explorer, and Safari), still require the
    standalone Selenium server.

Thus pioneer.js should allow using the Selenium standalone server. For that I suggest adding a CLI parameter as well as a new property in the pioneer.json. You could call it "selenium_standalone_url". The parameter should take the url of the running server. (The user should start it manually before invoking pioneer.) The url was `http://192.168.2.4:55142/wd/hub` in one of my tests. Just so you know how the url looks like in general.

The code change needed for that (besides introducing the new parameter) is in line 87 of src/support/index.coffee. Currently it contains:

``` coffee
@driver = new Driver.Builder().withCapabilities(Driver.Capabilities[argv.driver || 'chrome']()).build()
```

and should be extended by:

``` coffee
@driver = new Driver.Builder().usingServer(argv.selenium_standalone_url).withCapabilities(Driver.Capabilities[argv.driver || 'chrome']()).build()
```

Of course the `usingServer(...)` call should only be made if the parameter `selenium_standalone_url` is set.

With a little hacking to apply the enhancement quickly I was able to successfully execute a test in PhantomJS through my Selenium standalone server. After I removed the `usingServer(...)` call then pioneer was not able to run PhantomJS anymore. This way I made sure that I really used the Selenium standalone server.

BTW, I am using the "webdrvr" package for setting up the Selenium standalone server. The still a bit hacky code I use is:

``` js
var remote = require('./node_modules/pioneer/node_modules/selenium-webdriver/remote');
var webdrvr = require('webdrvr');

server = new remote.SeleniumServer(webdrvr.selenium.path, {
    args: webdrvr.args
});
server.start()
    .then(function(url) {
        // Here I execute pioneer with passing the url
    });
```

**Comment by mightyiam** [comment]
So, I can't use my own Selenium server? How will I test using multiple IEs that I have in VMs if I can't do that?

Seems like a deal breaker, for now.
