### ISSUE TITLE
error with events.js

### ISSUE THREAD

**Issue by orizens** [mojotech/pioneer#326]
hi.  
I updated pioneer to the latest version (0.10.5), and i'm getting this error:  
```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn EACCES
    at errnoException (child_process.js:1001:11)
    at Process.ChildProcess._handle.onexit (child_process.js:792:34)
```
am i missing something?

**Comment by samccone** [comment]
hey @orizens I will need a tiny bit more context can you provide your node version and some code to reproduce?

**Comment by orizens** [comment]
hi.  
You can clone my code at: https://github.com/orizens/echoes, and run pioneer in master branch.  
i'm using node version v0.10.33.  
The strange thing is that it works fine in a branch "angular", however in **master** it doesn't work.

**Comment by orizens** [comment]
I think that i've found the problem.
Apparently, the chromedriver file i'm using in master was corrupted.
Also, my code is dependant on the "selenium-driver" node module.
