### ISSUE TITLE
How to debug steps?

### ISSUE THREAD

**Issue by Danieler** [mojotech/pioneer#338]
I would like some help about how to debug feature steps
i tried with webstorm and node.js debugger but it don work...
any ideas?

**Comment by sethkrasnianski** [comment]
Using [Node Inspector](https://github.com/node-inspector/node-inspector) should work. If you toss a `debugger` in one of your step definitions and then in terminal, from your working directory, run...
```bash
☃ seth:~/pioneertest$ node-debug pioneer
```
This will kick off a developer tools window. It always puts a breakpoint on the first line of the entry file you're debugging. In this case it will be `var path  = require('path');`. Just hit play to continue to your `debugger`. After a moment, your `debugger` will trip and you'll se something like this...

<img width="878" alt="screen shot 2015-10-14 at 11 19 41 am" src="https://cloud.githubusercontent.com/assets/1910114/10488219/ab32432a-7265-11e5-8184-a77dec038f25.png">

You can now interact with your step definition as you would normally do so with browser code in Chrome Developer Tools. You'll notice that I was able to inspect the `value` in this example.

Hope that helps :+1: and let me know if you have any further questions.

**Comment by Danieler** [comment]
thanks a lot!! works perfectly!!
